version: 2

builds:
  - main: ./cmd/sgpt/main.go
    binary: sgpt
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

release:
  github:
    owner: ryanhe919
    name: llm-shell

checksum:
  name_template: "checksums.txt"